# Site settings
title: "Data Creative"
author: "MJ Rossetti"
description: "Data products and services brought to life."
source_url: "https://github.com/data-creative/data-creative.github.io"
url: "http://data-creative.info" # "http://data-creative.github.io"
baseurl: ""
twitter_username: data_creative
github_username:  data-creative
exclude: ["README.md"]
google_analytics_tracker_id: 'UA-61038121-1'

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis","tables","fenced_code_blocks","autolink","with_toc_data"] # https://github.com/vmg/redcarpet/blob/v2.2.2/README.markdown#and-its-like-really-simple-to-use
