# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://data-creative.github.io/
title: Data Creative
email: datacreativellc@gmail.com
author: MJ Rossetti
description: Data Creative specializes in data strategy, architecture, and engineering.
copyright: Copyright &copy; 2016 Data Creative, LLC.
repository: https://github.com/data-creative/data-creative.info/
#url: "http://data-creative.info"
baseurl: ""


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    fa-icon-class: envelope
    url: mailto:datacreativellc@gmail.com
  - title: twitter
    fa-icon-class: twitter
    url: https://twitter.com/data_creative
  - title: github
    fa-icon-class: github
    url: https://github.com/data-creative/
  #- title: linkedin
  #  url:

google_analytics_tracker_id: 'UA-61038121-1'
disqus_shortname: 's2t2info'
